
POST https://localhost:9443/sisdep/login
content-type: application/json

{
    "username": "admin",
    "password": "Pruebas@geosat"
}

###
GET https://localhost:9443/sisdep/api/seguridad/modulo
x-access: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJncm91cElkIjowLCJpc3MiOiJTRU5BIiwiaXBBZGRyZXNzIjoiMTI3LjAuMC4xIiwiZXhwIjoxNjQ1NzY1MjAwLCJ1c2VySWQiOjMsInVzZXJuYW1lIjoiMTAwMDAwMDAwIn0.evxucpX3QRsWNk0rdE-4bjHc4sUFCD7ppgYe52Ao_oRLWpIr7FBE-jz9u4bhUuxUmCYpMZU_91IqKmcMxd3eWg

###
GET https://localhost:9443/sisdep/api/seguridad/modulo/2
x-access: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJncm91cElkIjowLCJpc3MiOiJTRU5BIiwiaXBBZGRyZXNzIjoiMTI3LjAuMC4xIiwiZXhwIjoxNjQ1NzY1MjAwLCJ1c2VySWQiOjMsInVzZXJuYW1lIjoiMTAwMDAwMDAwIn0.evxucpX3QRsWNk0rdE-4bjHc4sUFCD7ppgYe52Ao_oRLWpIr7FBE-jz9u4bhUuxUmCYpMZU_91IqKmcMxd3eWg

###
GET https://localhost:9443/sisdep/api/seguridad/grupo
x-access: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJncm91cElkIjowLCJpc3MiOiJTRU5BIiwiaXBBZGRyZXNzIjoiMTI3LjAuMC4xIiwiZXhwIjoxNjQ1NzY1MjAwLCJ1c2VySWQiOjMsInVzZXJuYW1lIjoiMTAwMDAwMDAwIn0.evxucpX3QRsWNk0rdE-4bjHc4sUFCD7ppgYe52Ao_oRLWpIr7FBE-jz9u4bhUuxUmCYpMZU_91IqKmcMxd3eWg

###
GET https://localhost:9443/sisdep/api/seguridad/grupo/5
x-access: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJncm91cElkIjowLCJpc3MiOiJTRU5BIiwiaXBBZGRyZXNzIjoiMTI3LjAuMC4xIiwiZXhwIjoxNjQ1NzY1MjAwLCJ1c2VySWQiOjMsInVzZXJuYW1lIjoiMTAwMDAwMDAwIn0.evxucpX3QRsWNk0rdE-4bjHc4sUFCD7ppgYe52Ao_oRLWpIr7FBE-jz9u4bhUuxUmCYpMZU_91IqKmcMxd3eWg

###
GET https://localhost:9443/sisdep/api/seguridad/usuario
x-access: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJncm91cElkIjowLCJpc3MiOiJTRU5BIiwiaXBBZGRyZXNzIjoiMTI3LjAuMC4xIiwiZXhwIjoxNjQ1NzY1MjAwLCJ1c2VySWQiOjMsInVzZXJuYW1lIjoiMTAwMDAwMDAwIn0.evxucpX3QRsWNk0rdE-4bjHc4sUFCD7ppgYe52Ao_oRLWpIr7FBE-jz9u4bhUuxUmCYpMZU_91IqKmcMxd3eWg

###
POST https://localhost:9443/sisdep/api/seguridad/usuario
content-type: application/json
x-access: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJncm91cElkIjowLCJpc3MiOiJTRU5BIiwiaXBBZGRyZXNzIjoiMTI3LjAuMC4xIiwiZXhwIjoxNjQ1NzY1MjAwLCJ1c2VySWQiOjMsInVzZXJuYW1lIjoiMTAwMDAwMDAwIn0.evxucpX3QRsWNk0rdE-4bjHc4sUFCD7ppgYe52Ao_oRLWpIr7FBE-jz9u4bhUuxUmCYpMZU_91IqKmcMxd3eWg

{
    "nombre": "Jholman Daniel",
    "apellido": "Reina Toledo",
    "idTipoDocumento": "1",
    "identificacion": "10011990056",
    "email": "jdreinat@geosat.com.co",
    "activo": "true",
    "idGrupo": "1"
}

###
PATCH  https://localhost:9443/sisdep/api/seguridad/usuario/2
content-type: application/json
x-access: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJncm91cElkIjowLCJpc3MiOiJTRU5BIiwiaXBBZGRyZXNzIjoiMTI3LjAuMC4xIiwiZXhwIjoxNjQ1NzY1MjAwLCJ1c2VySWQiOjMsInVzZXJuYW1lIjoiMTAwMDAwMDAwIn0.evxucpX3QRsWNk0rdE-4bjHc4sUFCD7ppgYe52Ao_oRLWpIr7FBE-jz9u4bhUuxUmCYpMZU_91IqKmcMxd3eWg

{
    "id": "2",
    "nombre": "Jholman Daniel asd",
    "apellido": "Reina Toledo",
    "idTipoDocumento": "1",
    "identificacion": "1001199004",
    "email": "jdreinat@geosat.com.co",
    "activo": "true",
    "idGrupo": "1"
}

###

GET https://localhost:9443/sisdep/api/seguridad/usuario/ego
x-access: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJncm91cElkIjowLCJpc3MiOiJTRU5BIiwiaXBBZGRyZXNzIjoiMTI3LjAuMC4xIiwiZXhwIjoxNjQ2MDI0NDAwLCJ1c2VySWQiOjAsInVzZXJuYW1lIjoiMTAwMDAwMDAwIn0.8wzPlNt7BOyXNvMZb7O56gAJtcHThATmjwtCXzHJMZFxJfPfH7q0P2IcS4KQE4hWpyDkDGwXBSoW2MCy8CStBQ

###
GET https://localhost:9443/sisdep/api/social/datosPersonales
x-access: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJncm91cElkIjowLCJpc3MiOiJTRU5BIiwiaXBBZGRyZXNzIjoiMTI3LjAuMC4xIiwiZXhwIjoxNjQ2MTk3MjAwLCJ1c2VySWQiOjAsInVzZXJuYW1lIjoiMTAwMDAwMDAwIn0.U5MGsf2UsbuQ0WDS5v1MqAgtXUODeSXeLdmvh-j6EHQM9cUYfeNQ4coR7IE2GKZVA6Pj--86WYnS98Lbg0on9Q

###
GET https://localhost:9443/sisdep/api/social/estudioSocioEconomico
x-access: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJncm91cElkIjowLCJpc3MiOiJTSVNERVAiLCJpcEFkZHJlc3MiOiIxMjcuMC4wLjEiLCJleHAiOjE2NjAyODA0MDAsInVzZXJJZCI6MCwidXNlcm5hbWUiOiJhZG1pbiJ9.0F-7VQlV8eK8Cirl5k_UAZRotautkF-g-9PSkGVYK50LzTR9f5xJrYFmOiNxks-uDgj58rqSFd7SBfIhDaJ_6g


###
GET https://localhost:9443/sisdep/api/operativa/sectorInterno
x-access: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJncm91cElkIjowLCJpc3MiOiJTRU5BIiwiaXBBZGRyZXNzIjoiMTI3LjAuMC4xIiwiZXhwIjoxNjQ4MDk4MDAwLCJ1c2VySWQiOjAsInVzZXJuYW1lIjoiMTAwMDAwMDAwIn0.LmnS6C8p_ICYUEO5ceCFc0yPqz5mJuR4bKpU2AUleESgTUIipvNvwxS-wb-huE4CrCLCDLdgiy4KWBde7XlLkg

###
GET  https://localhost:9443/sisdep/api/regulaciones/reportes/asignacionModulos
GET  https://localhost:9443/sisdep/api/social/reportes/estudiosPorVentero
x-access: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJncm91cElkIjowLCJpc3MiOiJTRU5BIiwiaXBBZGRyZXNzIjoiMTI3LjAuMC4xIiwiZXhwIjoxNjQ5MzA3NjAwLCJ1c2VySWQiOjQsInVzZXJuYW1lIjoiMiJ9.FFxRcHgnSTWwJiKnGOwtmTkbTpi8dmNwxukyZYwhC6hQcuP3pVHL_oT9usf9XH4vNvU1uJDeiZyep3CAXEUXhA

###
GET  https://localhost:9443/sisdep/registro-entrega/1649849486533.jpg
x-access: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJncm91cElkIjowLCJpc3MiOiJTRU5BIiwiaXBBZGRyZXNzIjoiMTI3LjAuMC4xIiwiZXhwIjoxNjUwNDMwODAwLCJ1c2VySWQiOjEwLCJ1c2VybmFtZSI6IjIifQ.RSNqRvJTzRJQOTzXtpgeSECvRjXyz4raln5H0_wrBIpcxrth-AgqMTO6vN8n4OUyTaqML0CS-aB9IZ2aTQyTcg

###
GET  https://localhost:9443/sisdep/api/regulaciones/reportes/solicitudAutorizacionReporte
x-access: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJncm91cElkIjowLCJpc3MiOiJTSVNERVAiLCJpcEFkZHJlc3MiOiIxMjcuMC4wLjEiLCJleHAiOjE2NjAyODA0MDAsInVzZXJJZCI6MCwidXNlcm5hbWUiOiJhZG1pbiJ9.0F-7VQlV8eK8Cirl5k_UAZRotautkF-g-9PSkGVYK50LzTR9f5xJrYFmOiNxks-uDgj58rqSFd7SBfIhDaJ_6g