# --- Created by Ebean DDL
# To stop Ebean DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table sisdep_operativa.acta_inventario (
  id                            bigint generated by default as identity not null,
  nombre_policia                varchar(255),
  placa_policia                 varchar(255),
  pdf_acta                      varchar(255),
  es_nn                         boolean,
  id_direccion_incautacion      bigint,
  id_funcionario_acompana       bigint,
  fecha                         date,
  descripcion                   varchar(255),
  id_reconocimiento_incautacion bigint,
  id_descongestion              bigint,
  id_entrega                    bigint,
  constraint pk_acta_inventario primary key (id)
);

create table sisdep_general.actividad_economica_tipologica (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_actividad_economica_tipologica primary key (id)
);

create table sisdep_operativa.actividad_operativa (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_actividad_operativa primary key (id)
);

create table sisdep_general.actividad_prohibida (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_actividad_prohibida primary key (id)
);

create table sisdep_general.adicionales_amoblamiento (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_adicionales_amoblamiento primary key (id)
);

create table sisdep_ventero.amoblamiento (
  id                            bigint generated by default as identity not null,
  id_tenencia_propiedad         bigint,
  cual_empresa                  varchar(255),
  id_tipo_modulo                bigint,
  id_tipo_otro_modulo           bigint,
  id_estado                     bigint,
  tiene_servicios_publicos      boolean,
  id_conexion_agua              bigint,
  id_conexion_energia           bigint,
  id_conexion_gas               bigint,
  usa_pipeta                    boolean,
  capacidad_pipeta              float,
  frente                        float,
  fondo                         float,
  alto                          float,
  id_cubierta                   bigint[],
  id_material_amoblamiento      bigint[],
  constraint pk_amoblamiento primary key (id)
);

create table sisdep_operativa.archivos_sector_interno (
  id                            bigint generated by default as identity not null,
  id_sector_interno             bigint,
  enlace                        varchar(255),
  constraint pk_archivos_sector_interno primary key (id)
);

create table sisdep_regulaciones.vw_asignacion_modulos (
  id_modulo                     bigint generated by default as identity not null,
  id_ventero                    bigint,
  nombres_ventero               varchar(255),
  serial_propio                 varchar(255),
  id_tipo_modulo                bigint,
  id_sector_modulo              bigint,
  frente                        bigint,
  fondo                         bigint,
  alto                          bigint,
  es_vigente                    boolean,
  constraint pk_vw_asignacion_modulos primary key (id_modulo)
);

create table sisdep_social.aspectos_economicos (
  id                            bigint generated by default as identity not null,
  arriendo                      float,
  alimentacion                  float,
  transporte                    float,
  servicios_publicos            float,
  gastos_educativos             float,
  gastos_medicos                float,
  recreacion                    float,
  creditos                      float,
  bodegaje_puesto               float,
  arriendo_puesto               float,
  otros_gastos                  float,
  total_gastos                  float,
  ganancia_ventas               float,
  salarios                      float,
  pensiones                     float,
  arrendamientos                float,
  subsidio_caja_compensacion    float,
  subsidio_adulto_mayor         float,
  otros_subsidios               float,
  apoyos_economicos             float,
  otros_ingresos                float,
  total_ingresos                float,
  total_ingresos_gastos         float,
  observaciones                 varchar(255),
  ingreso_x_integrante          float,
  id_tipo_probreza              bigint,
  es_informal                   boolean,
  id_estudio_socioeconomico     bigint,
  ip                            varchar(255),
  id_usuario_edita              bigint,
  fecha_edita                   date,
  constraint pk_aspectos_economicos primary key (id)
);

create table sisdep_social.aspectos_familiares (
  id                            bigint generated by default as identity not null,
  id_tipologia_familiar         bigint,
  etapa_ciclo_vital             varchar(255),
  variable_relevantes           varchar(255),
  satisfecho_ayuda_familiar     bigint,
  conversa_problemas            bigint,
  desiciones_conjuntas          bigint,
  lo_quieren                    bigint,
  satisfecho_tiempo_familiar    bigint,
  puntaje_apgar                 float,
  id_estudio_socioeconomico     bigint,
  ip                            varchar(255),
  id_usuario_edita              bigint,
  fecha_edita                   date,
  constraint pk_aspectos_familiares primary key (id)
);

create table sisdep_social.aspectos_poblacionales (
  id                            bigint generated by default as identity not null,
  id_grupo_poblacional          bigint,
  es_desplazado                 boolean,
  lugar_desplazamiento          varchar(255),
  ano_desplazado                bigint,
  es_damnificado                boolean,
  pertenece_grupos_vendedores   boolean,
  grupo_vendedores              varchar(255),
  tiene_capacidad_diferencial   boolean,
  id_tipo_capacidad_diferencial bigint[],
  id_capacidad_diferencial      bigint[],
  pertenece_grupo_comunitario   boolean,
  id_grupo_comunitario          bigint[],
  capacitacion_administracion_municipal boolean,
  cual_capacitacion_administracion varchar(255),
  gustaria_programa_social      boolean,
  cual_programa_social          varchar(255),
  gustaria_programa_deportivo   boolean,
  cual_programa_deportivo       varchar(255),
  gustaria_educacion_formal     boolean,
  cual_educacion_formal         varchar(255),
  gustaria_educacion_informal   boolean,
  cual_educacion_informal       varchar(255),
  gustaria_programa_cultural    boolean,
  cual_programa_cultural        varchar(255),
  gustaria_programa_recreativo  boolean,
  cual_programa_recreativo      varchar(255),
  gustaria_programa_salud       boolean,
  cual_programa_salud           varchar(255),
  id_ocupacion_anterior         bigint[],
  id_motivo_labora_espacio_publico bigint[],
  otro_motivo                   varchar(255),
  artes_oficios                 varchar(255),
  id_estudio_socioeconomico     bigint,
  ip                            varchar(255),
  id_usuario_edita              bigint,
  fecha_edita                   date,
  constraint pk_aspectos_poblacionales primary key (id)
);

create table sisdep_social.aspectos_seguridad_social (
  id                            bigint generated by default as identity not null,
  es_pensionado                 boolean,
  empresa_pension               varchar(255),
  valor_pension                 float,
  es_jubilado                   boolean,
  id_entidad_jubilado           bigint,
  valor_jubilacion              float,
  tiene_sisben                  boolean,
  id_municipio_sisben           bigint,
  puntaje_sisben                bigint,
  grupo_sisben                  varchar(255),
  num_ficha                     varchar(255),
  tiene_eps                     boolean,
  id_tipo_afiliacion            bigint,
  id_eps                        bigint,
  cotiza_pension                boolean,
  id_cotiza_pension             bigint,
  id_entidad_cotiza_pension     bigint,
  tiene_arl                     boolean,
  id_cotiza_arl                 bigint,
  id_estudio_socioeconomico     bigint,
  ip                            varchar(255),
  id_usuario_edita              bigint,
  fecha_edita                   date,
  constraint pk_aspectos_seguridad_social primary key (id)
);

create table sisdep_social.aspectos_vivienda (
  id                            bigint generated by default as identity not null,
  direccion                     varchar(255),
  id_tenencia_propiedad         bigint,
  id_obtencion_propiedad        bigint,
  id_tipo_vivienda              bigint,
  valor_mes                     float,
  id_material_techo             bigint[],
  id_material_piso              bigint[],
  id_material_pared             bigint[],
  num_ventanas                  bigint,
  num_habitaciones              bigint,
  num_personas_habitacion       bigint,
  menores_con_adultos_pieza     boolean,
  vivienda_deteriorada          boolean,
  des_estado_vivienda           varchar(255),
  id_servicios_publicos         bigint[],
  observaciones                 varchar(255),
  id_estudio_socioeconomico     bigint,
  ip                            varchar(255),
  id_usuario_edita              bigint,
  fecha_edita                   date,
  constraint pk_aspectos_vivienda primary key (id)
);

create table sisdep_general.aviso_publicitario (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_aviso_publicitario primary key (id)
);

create table sisdep_general.aviso_publicitario_apro_economico (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_aviso_publicitario_apro_economico primary key (id)
);

create table sisdep_general.barrio (
  id                            bigint generated by default as identity not null,
  codigo                        varchar(255),
  descripcion                   varchar(100) not null,
  constraint pk_barrio primary key (id)
);

create table sisdep_general.capacidad_diferencial (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_capacidad_diferencial primary key (id)
);

create table sisdep_regulaciones.caracterizacion_ixi (
  id                            bigint generated by default as identity not null,
  id_direccion_transitoria      bigint,
  id_tipologia_transitoria      bigint,
  formato_caracterizacion       varchar(255),
  id_resolucion                 bigint,
  id_alternativa1               bigint,
  id_alternativa2               bigint,
  id_alternativa3               bigint,
  id_ventero                    bigint,
  id_intervencion               bigint,
  constraint pk_caracterizacion_ixi primary key (id)
);

create table sisdep_general.causal_estudio (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_causal_estudio primary key (id)
);

create table sisdep_general.clase_venta (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_clase_venta primary key (id)
);

create table sisdep_general.comuna (
  id                            bigint generated by default as identity not null,
  codigo                        varchar(255),
  descripcion                   varchar(100) not null,
  constraint pk_comuna primary key (id)
);

create table sisdep_social.concepto_vulnerabilidad (
  id                            bigint generated by default as identity not null,
  justificacion_vulnerabilidad  varchar(255),
  dinamica_familiar             varchar(255),
  concepto                      varchar(255),
  pasa_concepto                 boolean,
  grado_vulnerabilidad          bigint,
  id_exento_retribucion         bigint,
  valor_retribucion             bigint,
  catastro_municipal            varchar(255),
  runt                          varchar(255),
  rues                          varchar(255),
  sispro_ruaf                   varchar(255),
  sispro_pagos                  varchar(255),
  arl                           varchar(255),
  afp                           varchar(255),
  victimas_conflicto            varchar(255),
  concepto_bd_revalidacion      varchar(255),
  concepto_sisdep               varchar(255),
  resultado_cruce               varchar(255),
  cumple_cruce                  boolean,
  id_estudio_socioeconomico     bigint,
  ip                            varchar(255),
  id_usuario_edita              bigint,
  fecha_edita                   date,
  constraint pk_concepto_vulnerabilidad primary key (id)
);

create table sisdep_general.convenio (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_convenio primary key (id)
);

create table sisdep_general.cubierta (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_cubierta primary key (id)
);

create table sisdep_social.datos_personales (
  id                            bigint generated by default as identity not null,
  tiene_personas_cargo          boolean,
  num_personas_cargo            bigint,
  telefono_familiar             bigint,
  telefono_amigo                bigint,
  id_estudio_socioeconomico     bigint,
  ip                            varchar(255),
  id_usuario_edita              bigint,
  fecha_edita                   date,
  constraint pk_datos_personales primary key (id)
);

create table sisdep_ventero.datos_venta (
  id                            bigint generated by default as identity not null,
  id_clase_venta                bigint,
  id_direccion                  bigint,
  id_costado                    bigint,
  id_tipologia_venta            bigint,
  id_actividad_economica_actual bigint,
  des_actividad_economica       varchar(255),
  id_actividad_economica_opcional bigint,
  atiende_titular               boolean,
  observaciones                 varchar(255),
  id_ventero                    bigint,
  id_sector_interno             bigint,
  id_dia                        bigint[],
  hora_inicio                   bigint,
  hora_fin                      bigint,
  id_amoblamiento               bigint,
  constraint pk_datos_venta primary key (id)
);

create table sisdep_operativa.descongestion (
  id                            bigint generated by default as identity not null,
  nombre_quien_recibe           varchar(255),
  documento_quien_recibe        varchar(255),
  fecha                         date,
  numero_resolucion             bigint,
  fecha_resolucion              date,
  observaciones                 varchar(255),
  pdf_resolucion                varchar(255),
  id_usuario                    bigint,
  constraint pk_descongestion primary key (id)
);

create table sisdep_general.dia_semana (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_dia_semana primary key (id)
);

create table sisdep_general.direccion (
  id                            bigint generated by default as identity not null,
  cruce_desde                   bigint,
  numero_desde                  bigint,
  letra_desde                   varchar(255),
  orientacion_desde             bigint,
  cruce_hasta                   bigint,
  numero_hasta                  bigint,
  letra_hasta                   varchar(255),
  orientacion_hasta             bigint,
  numero                        bigint,
  complemento                   varchar(255),
  id_municipio                  bigint,
  id_barrio                     bigint,
  id_comuna                     bigint,
  localizacion                  geometry(point,4326),
  ip                            varchar(255),
  id_usuario_edita              bigint,
  fecha_edita                   date,
  constraint pk_direccion primary key (id)
);

create table sisdep_operativa.elemento_entregado (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(255),
  cantidad                      bigint,
  serial_elemento               varchar(255),
  id_tarea_operativa            bigint,
  constraint pk_elemento_entregado primary key (id)
);

create table sisdep_general.elemento_medicion (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_elemento_medicion primary key (id)
);

create table sisdep_operativa.entidad_apoyo (
  id                            bigint generated by default as identity not null,
  id_entidad                    bigint,
  nombre_encargado              varchar(255),
  id_tarea_operativa            bigint,
  constraint pk_entidad_apoyo primary key (id)
);

create table sisdep_operativa.entidad_apoyo_operativa (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_entidad_apoyo_operativa primary key (id)
);

create table sisdep_general.entidad_jubilacion (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_entidad_jubilacion primary key (id)
);

create table sisdep_operativa.entrega (
  id                            bigint generated by default as identity not null,
  nombre_quien_recibe           varchar(255),
  documento_quien_recibe        varchar(255),
  observaciones                 varchar(255),
  fecha                         date,
  id_usuario                    bigint,
  constraint pk_entrega primary key (id)
);

create table sisdep_general.eps (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_eps primary key (id)
);

create table sisdep_general.escolaridad (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_escolaridad primary key (id)
);

create table sisdep_general.estado (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_estado primary key (id)
);

create table sisdep_general.estado_autorizacion (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_estado_autorizacion primary key (id)
);

create table sisdep_general.estado_civil (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_estado_civil primary key (id)
);

create table sisdep_general.estado_recurso (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_estado_recurso primary key (id)
);

create table sisdep_social.estudio_socio_economico (
  id                            bigint generated by default as identity not null,
  id_causal_estudio             bigint,
  id_visita_domiciliaria        bigint,
  fecha_firma                   date,
  id_usuario_firma              bigint,
  ip                            varchar(255),
  id_usuario_edita              bigint,
  fecha_edita                   date,
  constraint pk_estudio_socio_economico primary key (id)
);

create table sisdep_social.vw_estudios_por_ventero (
  id_visita_domiciliaria        bigint generated by default as identity not null,
  nombres                       varchar(255),
  apellidos                     varchar(255),
  documento                     varchar(255),
  fecha_visita                  timestamptz,
  nombre_visitador              varchar(255),
  apellido_visitador            varchar(255),
  identificacion_visitador      varchar(255),
  fecha_firma                   date,
  nombre_firmante               varchar(255),
  apellido_firmante             varchar(255),
  identificacion_firmante       varchar(255),
  constraint pk_vw_estudios_por_ventero primary key (id_visita_domiciliaria)
);

create table sisdep_operativa.evidencia_recuperacion (
  id                            bigint generated by default as identity not null,
  enlace                        varchar(255),
  fecha                         date,
  id_solicitud_recuperacion_espacio_publico bigint,
  constraint pk_evidencia_recuperacion primary key (id)
);

create table sisdep_social.evidencias_oferta (
  id                            bigint generated by default as identity not null,
  id_tipo_evidencia             bigint,
  id_oferta                     bigint,
  enlace                        varchar(255),
  constraint pk_evidencias_oferta primary key (id)
);

create table sisdep_general.exento_retribucion (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_exento_retribucion primary key (id)
);

create table sisdep_operativa.fase_indicador (
  id                            bigint generated by default as identity not null,
  numero                        bigint,
  periodo                       date,
  meta                          bigint,
  ejecucion                     bigint,
  id_indicadores_sector_interno bigint,
  constraint pk_fase_indicador primary key (id)
);

create table sisdep_general.finalidad_valla (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_finalidad_valla primary key (id)
);

create table sisdep_general.fondo_pension (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_fondo_pension primary key (id)
);

create table sisdep_general.franja_horaria (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_franja_horaria primary key (id)
);

create table sisdep_administracion.grupo (
  id                            bigint generated by default as identity not null,
  nombre                        varchar(100) not null,
  descripcion                   varchar(255) not null,
  es_social                     boolean not null,
  es_operativo                  boolean not null,
  es_pev                        boolean not null,
  constraint pk_grupo primary key (id)
);

create table sisdep_general.grupo_comunitario (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_grupo_comunitario primary key (id)
);

create table sisdep_general.grupo_poblacional (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_grupo_poblacional primary key (id)
);

create table sisdep_general.grupo_sisben (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_grupo_sisben primary key (id)
);

create table sisdep_general.indicador_parametro (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_indicador_parametro primary key (id)
);

create table sisdep_operativa.indicadores_sector_interno (
  id                            bigint generated by default as identity not null,
  indicadores                   varchar(255),
  fuente_verificacion           varchar(255),
  meta                          bigint,
  anio                          bigint,
  id_sector_interno             bigint,
  constraint pk_indicadores_sector_interno primary key (id)
);

create table sisdep_ventero.integrante_nucleo_familiar (
  id                            bigint generated by default as identity not null,
  id_estado_civil               bigint,
  id_parentesco                 bigint,
  id_escolaridad                bigint,
  id_ocupacion                  bigint,
  id_tipo_ocupacion             bigint,
  puntaje_sisben                varchar(255),
  id_tipo_aficiacion_salud      bigint,
  id_grupo_especial_proteccion  bigint[],
  capacidad_diferencial         boolean,
  id_tipo_capacidad_diferencial bigint[],
  enfermedades_catastroficas_terminales boolean,
  es_adicto                     boolean,
  observaciones                 varchar(255),
  es_desplazado                 boolean,
  es_damnificado                boolean,
  personas_cargo                boolean,
  id_ventero                    bigint,
  id_estudio_socioeconomico     bigint,
  constraint pk_integrante_nucleo_familiar primary key (id)
);

create table sisdep_regulaciones.intervencion_x_infraestructura (
  id                            bigint generated by default as identity not null,
  id_motivo_intervencion        bigint,
  fecha_registro                date,
  constraint pk_intervencion_x_infraestructura primary key (id)
);

create table sisdep_general.item_elemento_publicitario (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_item_elemento_publicitario primary key (id)
);

create table sisdep_operativa.item_retencion (
  id                            bigint generated by default as identity not null,
  id_item                       bigint,
  cantidad                      bigint,
  id_estado_elemento            bigint,
  descripcion                   varchar(255),
  id_retencion                  bigint,
  constraint pk_item_retencion primary key (id)
);

create table sisdep_general.item_retenido (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  es_publicidad                 boolean,
  constraint pk_item_retenido primary key (id)
);

create table sisdep_general.item_valla (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_item_valla primary key (id)
);

create table sisdep_general.ixi_anexo (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_ixi_anexo primary key (id)
);

create table sisdep_regulaciones.ixi_anexos (
  id                            bigint generated by default as identity not null,
  id_tipo_anexo_ixi             bigint,
  enlace                        varchar(255),
  id_intervencion               bigint,
  constraint pk_ixi_anexos primary key (id)
);

create table sisdep_general.jornada (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_jornada primary key (id)
);

create table sisdep_general.material_amueblamiento (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_material_amueblamiento primary key (id)
);

create table sisdep_general.material_pared (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_material_pared primary key (id)
);

create table sisdep_general.material_piso (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_material_piso primary key (id)
);

create table sisdep_general.material_techo (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_material_techo primary key (id)
);

create table sisdep_operativa.miembro_equipo_sector_interno (
  id                            bigint generated by default as identity not null,
  id_tipo_miembro               bigint,
  id_sector_interno             bigint,
  id_usuario                    bigint,
  constraint pk_miembro_equipo_sector_interno primary key (id)
);

create table sisdep_operativa.miembro_tarea_operativa (
  id                            bigint generated by default as identity not null,
  horas_servicio                bigint,
  observaciones                 varchar(255),
  id_usuario                    bigint,
  id_usuario_registra           bigint,
  id_tarea_operativa            bigint,
  constraint pk_miembro_tarea_operativa primary key (id)
);

create table sisdep_general.modulo (
  id                            bigint generated by default as identity not null,
  serial_propio                 varchar(255),
  id_tenencia_propiedad         bigint,
  ip                            varchar(255),
  id_usuario_edita              bigint,
  fecha_edita                   date,
  cual_empresa                  varchar(255),
  id_tipo_modulo                bigint,
  id_tipo_otro_modulo           bigint,
  id_estado                     bigint,
  tiene_servicios_publicos      boolean,
  id_conexion_agua              bigint,
  id_conexion_energia           bigint,
  id_conexion_gas               bigint,
  usa_pipeta                    boolean,
  capacidad_pipeta              float,
  frente                        float,
  fondo                         float,
  alto                          float,
  id_cubierta                   bigint[],
  id_material_amoblamiento      bigint[],
  id_direccion                  bigint,
  id_sector_modulo              bigint,
  constraint pk_modulo primary key (id)
);

create table sisdep_administracion.modulo_sistema (
  id                            bigint generated by default as identity not null,
  nombre                        varchar(100),
  nombre_externo                varchar(100),
  orden                         smallint,
  descripcion                   varchar(255),
  constraint pk_modulo_sistema primary key (id)
);

create table sisdep_general.motivo_autorizacion (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_motivo_autorizacion primary key (id)
);

create table sisdep_general.motivo_intervencion_infraestructura (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_motivo_intervencion_infraestructura primary key (id)
);

create table sisdep_general.motivo_labora_espacio_publico (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_motivo_labora_espacio_publico primary key (id)
);

create table sisdep_general.motivo_recuperacion (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_motivo_recuperacion primary key (id)
);

create table sisdep_general.municipio (
  id                            bigint generated by default as identity not null,
  codigo                        varchar(255),
  descripcion                   varchar(100) not null,
  constraint pk_municipio primary key (id)
);

create table sisdep_general.nacionalidad (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_nacionalidad primary key (id)
);

create table sisdep_social.necesidad (
  id                            bigint generated by default as identity not null,
  id_tipo_necesidad             bigint,
  descripcion                   varchar(255),
  id_usuario_elabora            bigint,
  id_persona                    bigint,
  constraint pk_necesidad primary key (id)
);

create table sisdep_general.nomenclatura_vial (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_nomenclatura_vial primary key (id)
);

create table sisdep_regulaciones.notificacion (
  id                            bigint generated by default as identity not null,
  numero_radicado_entrada       varchar(255),
  fecha_entrada                 date,
  numero_radicado_salida        varchar(255),
  fecha_salida                  date,
  nombre                        varchar(255),
  id_direccion                  bigint,
  telefono                      bigint,
  fecha_primera_citacion        date,
  fecha_envio_segunda           date,
  guia                          varchar(255),
  empresa_transportadora        varchar(255),
  publicado_cartelera           boolean,
  id_tipo                       bigint,
  id_recurso                    bigint,
  id_resolucion                 bigint,
  evidencia_guia                varchar(255),
  ip                            varchar(255),
  id_usuario_edita              bigint,
  fecha_edita                   date,
  constraint pk_notificacion primary key (id)
);

create table sisdep_general.obtencion_propiedad (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_obtencion_propiedad primary key (id)
);

create table sisdep_general.ocupacion (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_ocupacion primary key (id)
);

create table sisdep_social.oferta (
  id                            bigint generated by default as identity not null,
  fecha_ejecucion               date,
  id_tipo                       bigint,
  id_convenio                   bigint,
  constraint pk_oferta primary key (id)
);

create table sisdep_general.orientacion (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_orientacion primary key (id)
);

create table sisdep_general.parentesco (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_parentesco primary key (id)
);

create table sisdep_social.participante_oferta (
  id                            bigint generated by default as identity not null,
  id_tipo_conocimiento          bigint,
  es_efectivo                   boolean,
  participa_ventero             boolean,
  id_ventero                    bigint,
  id_integrante                 bigint,
  id_oferta                     bigint,
  constraint pk_participante_oferta primary key (id)
);

create table sisdep_administracion.permisos_x_modulo_x_grupo (
  id                            bigint generated by default as identity not null,
  leer                          boolean not null,
  escribir                      boolean not null,
  borrar                        boolean not null,
  exportar                      boolean not null,
  id_modulo_sistema             bigint not null,
  id_grupo                      bigint not null,
  constraint pk_permisos_x_modulo_x_grupo primary key (id)
);

create table sisdep_ventero.persona (
  id                            bigint generated by default as identity not null,
  nombre1                       varchar(255),
  nombre2                       varchar(255),
  apellido1                     varchar(255),
  apellido2                     varchar(255),
  id_tipo_documento             bigint,
  documento                     varchar(255),
  fecha_expedicion              date,
  id_nacionalidad               bigint,
  correo_electronico            varchar(255),
  id_direccion_residencia       bigint,
  fecha_registro                date,
  id_sexo                       bigint,
  id_tipo_persona               bigint,
  es_formal                     boolean,
  telefono_celular              bigint,
  telefono_fijo                 bigint,
  fecha_nacimiento              date,
  ip                            varchar(255),
  id_usuario_edita              bigint,
  fecha_edita                   date,
  constraint pk_persona primary key (id)
);

create table sisdep_general.persona_atiende (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_persona_atiende primary key (id)
);

create table sisdep_ventero.vw_personas_reporte (
  id                            bigint generated by default as identity not null,
  nombres                       varchar(255),
  apellidos                     varchar(255),
  documento                     varchar(255),
  tipo_documento                varchar(255),
  fecha_expedicion              date,
  nacionalidad                  varchar(255),
  sexo                          varchar(255),
  telefono_celular              bigint,
  telefono_fijo                 bigint,
  es_formal                     varchar(255),
  es_regulado                   varchar(255),
  tipo_persona                  varchar(255),
  edad                          bigint,
  grupo_sisben                  varchar(255),
  sector_interno                varchar(255),
  fecha_firma                   date,
  usuario_firma_nombre          varchar(255),
  usuario_firma_apellido        varchar(255),
  url                           varchar(255),
  fecha_inicial                 date,
  fecha_final                   date,
  estado_autorizacion           varchar(255),
  actividad_economica_actual    varchar(255),
  actividad_economica_opcional  varchar(255),
  tipologia_venta               varchar(255),
  dias                          varchar(255),
  hora_inicio                   bigint,
  hora_fin                      bigint,
  frente                        bigint,
  fondo                         bigint,
  alto                          bigint,
  clase_venta                   varchar(255),
  tipo_modulo                   varchar(255),
  proteccion_constitucional     varchar(255),
  capacidad_diferencial         varchar(255),
  municipio_venta               varchar(255),
  cruce_desde_venta             varchar(255),
  numero_desde_venta            varchar(255),
  letra_desde_venta             varchar(255),
  cruce_hasta_venta             varchar(255),
  numero_hasta_venta            varchar(255),
  letra_hasta_venta             varchar(255),
  barrio_venta                  varchar(255),
  comuna_venta                  varchar(255),
  municipio_vivienda            varchar(255),
  cruce_desde_vivienda          varchar(255),
  numero_desde_vivienda         varchar(255),
  letra_desde_vivienda          varchar(255),
  cruce_hasta_vivienda          varchar(255),
  numero_hasta_vivienda         varchar(255),
  letra_hasta_vivienda          varchar(255),
  barrio_vivienda               varchar(255),
  comuna_vivienda               varchar(255),
  fecha_radicado_solicitud      date,
  constraint pk_vw_personas_reporte primary key (id)
);

create table sisdep_general.programa_o_entidad (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_programa_o_entidad primary key (id)
);

create table sisdep_general.proteccion_constitucional (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_proteccion_constitucional primary key (id)
);

create table sisdep_operativa.reconocimiento_incautacion (
  id                            bigint generated by default as identity not null,
  elementos_incautados          varchar(255),
  senales_reconocimiento        varchar(255),
  id_usuario_diligencia         bigint,
  id_persona                    bigint,
  constraint pk_reconocimiento_incautacion primary key (id)
);

create table sisdep_regulaciones.recurso (
  id                            bigint generated by default as identity not null,
  fecha_expedicion              date,
  fecha_notificacion            date,
  id_tipo_recurso               bigint,
  id_estado                     bigint,
  id_resolucion                 bigint,
  ip                            varchar(255),
  id_usuario_edita              bigint,
  fecha_edita                   date,
  constraint pk_recurso primary key (id)
);

create table sisdep_regulaciones.registro_entrega_modulo (
  id                            bigint generated by default as identity not null,
  foto_entrega                  varchar(255),
  acta_entrega                  varchar(255),
  acta_inventario               varchar(255),
  id_modulo                     bigint,
  ip                            varchar(255),
  id_usuario_edita              bigint,
  fecha_edita                   date,
  constraint pk_registro_entrega_modulo primary key (id)
);

create table sisdep_social.remision (
  id                            bigint generated by default as identity not null,
  id_remitido_a                 bigint,
  fecha                         date,
  observaciones                 varchar(255),
  id_usuario_remite             bigint,
  id_necesidad                  bigint,
  constraint pk_remision primary key (id)
);

create table sisdep_general.remision_oferta (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_remision_oferta primary key (id)
);

create table sisdep_regulaciones.vw_reporte_modulos (
  id                            bigint generated by default as identity not null,
  documento                     varchar(255),
  tipo_documento                varchar(255),
  nombres_ventero               varchar(255),
  serial_propio                 varchar(255),
  tipo_modulo                   varchar(255),
  sector_modulo                 varchar(255),
  constraint pk_vw_reporte_modulos primary key (id)
);

create table sisdep_social.vw_reporte_participantes (
  id                            bigint generated by default as identity not null,
  tipo_conocimiento             varchar(255),
  es_efectivo                   varchar(255),
  id_oferta                     varchar(255),
  documento_ventero             varchar(255),
  tipo_documento_ventero        varchar(255),
  nombre1_ventero               varchar(255),
  nombre2_ventero               varchar(255),
  apellido1_ventero             varchar(255),
  apellido2_ventero             varchar(255),
  fecha_nacimiento_ventero      date,
  parentesco                    varchar(255),
  tipo_documento_integrante     varchar(255),
  documento_integrante          varchar(255),
  nombre1_integrante            varchar(255),
  nombre2_integrante            varchar(255),
  apellido1_integrante          varchar(255),
  apellido2_integrante          varchar(255),
  fecha_nacimiento_integrante   date,
  constraint pk_vw_reporte_participantes primary key (id)
);

create table sisdep_regulaciones.resolucion (
  id                            bigint generated by default as identity not null,
  fecha_efectos_fiscales        date,
  fecha_expedicion              date,
  fecha_notificacion            date,
  autoriza                      boolean,
  enlace_pdf_mercurio           varchar(255),
  id_tipologia_venta            bigint,
  id_tipo_resuelve              bigint,
  notificar_tramite             boolean,
  id_registro_entrega           bigint,
  ip                            varchar(255),
  id_usuario_edita              bigint,
  fecha_edita                   date,
  constraint pk_resolucion primary key (id)
);

create table sisdep_general.resuelve_resolucion (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_resuelve_resolucion primary key (id)
);

create table sisdep_general.resultado_visita_pev (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_resultado_visita_pev primary key (id)
);

create table sisdep_operativa.retencion (
  id                            bigint generated by default as identity not null,
  numero_retencion              varchar(255),
  fecha_registro                date,
  id_tipo_infraccion            bigint,
  notas_bodega                  varchar(255),
  es_publicidad                 boolean,
  id_usuario_recibe             bigint,
  id_acta_inventario            bigint,
  constraint pk_retencion primary key (id)
);

create table sisdep_operativa.sector_interno (
  id                            bigint generated by default as identity not null,
  nombre                        varchar(255),
  id_coordinador                bigint,
  plan_estrategico              varchar(255),
  constraint pk_sector_interno primary key (id)
);

create table sisdep_general.sector_modulos (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  prefijo                       varchar(255),
  constraint pk_sector_modulos primary key (id)
);

create table sisdep_regulaciones.seguimiento (
  id                            bigint generated by default as identity not null,
  id_quien                      bigint,
  fecha                         date,
  observacion                   varchar(255),
  id_notificacion               bigint,
  ip                            varchar(255),
  id_usuario_edita              bigint,
  fecha_edita                   date,
  constraint pk_seguimiento primary key (id)
);

create table sisdep_operativa.sensibilizacion (
  id                            bigint generated by default as identity not null,
  id_actividad_prohibida        bigint[],
  id_sitio_prohibido            bigint[],
  fecha                         date,
  id_tipo                       bigint,
  id_usuario                    bigint,
  numero_serie                  varchar(255),
  id_persona                    bigint,
  id_tarea_operativa            bigint,
  constraint pk_sensibilizacion primary key (id)
);

create table sisdep_operativa.sensibilizacion_formales (
  id                            bigint generated by default as identity not null,
  nombre_establecimiento        varchar(255),
  cumple_actividad_economica    boolean,
  auto_avisos_publicitarios     boolean,
  canti_avisos_publicitarios    boolean,
  auto_mesas_sillas             boolean,
  canti_mesas_sillas            boolean,
  auto_juegos_mecanicos         boolean,
  canti_juegos_mecanicos        boolean,
  auto_bazares                  boolean,
  canti_bazares                 boolean,
  realiza_actividad_prohibida   boolean,
  id_sensibilizacion            bigint,
  constraint pk_sensibilizacion_formales primary key (id)
);

create table sisdep_operativa.sensibilizacion_informales (
  id                            bigint generated by default as identity not null,
  cumple_clase_venta            boolean,
  cumple_actividad_economica    boolean,
  ocupacion_aprovechamiento     boolean,
  aprovechamiento_economico     boolean,
  actividad_prohibida           boolean,
  id_sensibilizacion            bigint,
  constraint pk_sensibilizacion_informales primary key (id)
);

create table sisdep_general.servicio_publico (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_servicio_publico primary key (id)
);

create table sisdep_general.sexo (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_sexo primary key (id)
);

create table sisdep_general.sitio_prohibido (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_sitio_prohibido primary key (id)
);

create table sisdep_regulaciones.solicitud_autorizacion (
  id                            bigint generated by default as identity not null,
  radicado_mercurio             varchar(255),
  id_motivo_autorizacion        bigint,
  id_titular                    bigint,
  fecha_inicial                 date,
  fecha_final                   date,
  id_direccion                  bigint,
  id_usuario_radica             bigint,
  concepto_tecnico              varchar(255),
  concepto_juridico             varchar(255),
  concepto_financiero           varchar(255),
  id_estado_autorizacion        bigint,
  id_resolucion                 bigint,
  id_dia                        bigint[],
  hora_inicio                   bigint,
  hora_fin                      bigint,
  ip                            varchar(255),
  id_usuario_edita              bigint,
  fecha_edita                   date,
  id_visita_domiciliaria        bigint,
  constraint pk_solicitud_autorizacion primary key (id)
);

create table sisdep_regulaciones.vw_solicitud_autorizacion_reporte (
  id                            bigint generated by default as identity not null,
  nombres                       varchar(255),
  apellidos                     varchar(255),
  documento                     varchar(255),
  tipo_documento                varchar(255),
  radicado_mercurio             varchar(255),
  motivo_autorizacion           varchar(255),
  fecha_inicial                 date,
  fecha_final                   date,
  municipio                     varchar(255),
  comuna                        varchar(255),
  barrio                        varchar(255),
  cruce_desde                   varchar(255),
  numero_desde                  bigint,
  letra_desde                   varchar(255),
  cruce_hasta                   varchar(255),
  numero_hasta                  bigint,
  letra_hasta                   varchar(255),
  usuario_radica_nombre         varchar(255),
  usuario_radica_apellido       varchar(255),
  usuario_radica_documento      varchar(255),
  usuario_radica_correo         varchar(255),
  concepto_tecnico              varchar(255),
  concepto_juridico             varchar(255),
  concepto_financiero           varchar(255),
  dias                          varchar(255),
  hora_inicio                   bigint,
  hora_fin                      bigint,
  constraint pk_vw_solicitud_autorizacion_reporte primary key (id)
);

create table sisdep_operativa.solicitud_recuperacion_espacio_publico (
  id                            bigint generated by default as identity not null,
  radicado_mercurio             varchar(255),
  id_motivo_recuperacion        bigint,
  se_remite_policia             boolean,
  acto_administrativo           varchar(255),
  id_sector_interno             bigint,
  fecha_solicitud               date,
  fecha_ejecucion               date,
  id_direccion                  bigint,
  id_tarea_operativa            bigint,
  id_acta_inventario            bigint,
  constraint pk_solicitud_recuperacion_espacio_publico primary key (id)
);

create table sisdep_operativa.tarea_operativa (
  id                            bigint generated by default as identity not null,
  fecha                         date,
  hora_inicio                   bigint,
  hora_fin                      bigint,
  id_sector_interno             bigint,
  id_direccion                  bigint,
  id_tipo_actividad             bigint,
  empresa_contratista           varchar(255),
  objetivo                      varchar(255),
  descripcion                   varchar(255),
  id_vehiculo_acompana          bigint,
  constraint pk_tarea_operativa primary key (id)
);

create table sisdep_general.tenencia_propiedad (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_tenencia_propiedad primary key (id)
);

create table sisdep_general.tenencia_vivienda (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_tenencia_vivienda primary key (id)
);

create table sisdep_ventero.tercero_atiende (
  id                            bigint generated by default as identity not null,
  id_tipo_persona_atiente       bigint,
  nombres                       varchar(255),
  apellidos                     varchar(255),
  id_tipo_documento             bigint,
  documento                     varchar(255),
  id_datos_venta                bigint,
  constraint pk_tercero_atiende primary key (id)
);

create table sisdep_general.tipo_afiliacion (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_tipo_afiliacion primary key (id)
);

create table sisdep_general.tipo_capacidad_diferencial (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_tipo_capacidad_diferencial primary key (id)
);

create table sisdep_general.tipo_conexion_servicio (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_tipo_conexion_servicio primary key (id)
);

create table sisdep_general.tipo_conocimiento (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_tipo_conocimiento primary key (id)
);

create table sisdep_general.tipo_cotiza (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_tipo_cotiza primary key (id)
);

create table sisdep_general.tipo_documento (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_tipo_documento primary key (id)
);

create table sisdep_general.tipo_evidencia (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_tipo_evidencia primary key (id)
);

create table sisdep_general.tipo_infraccion (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_tipo_infraccion primary key (id)
);

create table sisdep_general.tipo_instalacion (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_tipo_instalacion primary key (id)
);

create table sisdep_general.tipo_miembro_sector_interno (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_tipo_miembro_sector_interno primary key (id)
);

create table sisdep_general.tipo_misional (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_tipo_misional primary key (id)
);

create table sisdep_general.tipo_mixtura_suelo (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_tipo_mixtura_suelo primary key (id)
);

create table sisdep_general.tipo_modulo (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  prefijo                       varchar(255),
  constraint pk_tipo_modulo primary key (id)
);

create table sisdep_general.tipo_modulo_otro (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_tipo_modulo_otro primary key (id)
);

create table sisdep_general.tipo_necesidad (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_tipo_necesidad primary key (id)
);

create table sisdep_general.tipo_notificacion (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_tipo_notificacion primary key (id)
);

create table sisdep_general.tipo_ocupacion (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_tipo_ocupacion primary key (id)
);

create table sisdep_general.tipo_oferta (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_tipo_oferta primary key (id)
);

create table sisdep_general.tipo_permanencia (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_tipo_permanencia primary key (id)
);

create table sisdep_general.tipo_persona (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_tipo_persona primary key (id)
);

create table sisdep_general.tipo_pobreza (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_tipo_pobreza primary key (id)
);

create table sisdep_general.tipo_publicidad (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_tipo_publicidad primary key (id)
);

create table sisdep_general.tipo_recurso (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_tipo_recurso primary key (id)
);

create table sisdep_general.tipo_sensibilizacion (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_tipo_sensibilizacion primary key (id)
);

create table sisdep_general.tipo_solicitud (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_tipo_solicitud primary key (id)
);

create table sisdep_general.tipo_vehiculo (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_tipo_vehiculo primary key (id)
);

create table sisdep_general.tipo_visita (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  color                         varchar(7),
  constraint pk_tipo_visita primary key (id)
);

create table sisdep_general.tipo_vivienda (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_tipo_vivienda primary key (id)
);

create table sisdep_general.tipologia_familiar (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_tipologia_familiar primary key (id)
);

create table sisdep_general.tipologia_original (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_tipologia_original primary key (id)
);

create table sisdep_general.tipologia_transitoria (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  constraint pk_tipologia_transitoria primary key (id)
);

create table sisdep_administracion.usuario (
  id                            bigint generated by default as identity not null,
  nombres                       varchar(100) not null,
  apellidos                     varchar(100) not null,
  constraint pk_usuario primary key (id)
);

create table sisdep_general.valores_apgar (
  id                            bigint generated by default as identity not null,
  descripcion                   varchar(100) not null,
  puntaje                       bigint not null,
  constraint pk_valores_apgar primary key (id)
);

create table sisdep_general.vehiculo (
  id                            bigint generated by default as identity not null,
  nombre_conductor              varchar(255),
  placa                         varchar(255),
  id_tipo_vehiculo              bigint,
  constraint pk_vehiculo primary key (id)
);

create table sisdep_ventero.ventero (
  id                            bigint generated by default as identity not null,
  es_regulado                   boolean,
  id_estado_civil               bigint,
  id_proteccion_constitucional  bigint[],
  asociacion_participa          varchar(255),
  puntaje_sisben                float,
  grupo_sisben                  bigint,
  id_municipio_sisben           bigint,
  id_tipo_capacidad_diferencial bigint[],
  id_capacidad_diferencial      bigint[],
  id_escolaridad                bigint,
  titulo_obtenido               varchar(255),
  municipio_nacimiento          varchar(255),
  departamento_nacimiento       varchar(255),
  es_cancelado                  boolean,
  motivo_cancelado              varchar(255),
  enlace_escaner_formato        varchar(255),
  id_usuario_registra           bigint,
  modulo                        varchar(255),
  estate                        varchar(255),
  caja                          varchar(255),
  hoja_vida_prestada            boolean,
  enlace                        varchar(255),
  estrato                       bigint,
  ip                            varchar(255),
  id_usuario_edita              bigint,
  fecha_edita                   date,
  constraint pk_ventero primary key (id)
);

create table sisdep_regulaciones.visita_administrativa (
  id                            bigint generated by default as identity not null,
  fecha                         date,
  existe_venta                  boolean,
  atiente_titular               boolean,
  venta_cerrada                 boolean,
  espacio_bodega                boolean,
  cumple_tipologia              boolean,
  venta_especifica              varchar(255),
  cumple_horario                boolean,
  direccion_distintas_asignada  varchar(255),
  frente_amoblamiento           float,
  fondo_amoblamiento            float,
  alto_amoblamiento             float,
  frente_exhibicion             float,
  fondo_exhibicion              float,
  alto_exhibicion               float,
  supera_medidas_autorizadas    boolean,
  tiene_adicionales             boolean,
  id_adicionales                bigint[],
  id_tipo_mixtura               bigint,
  tiene_carnet_alimentos        boolean,
  utiliza_publicidad_exterior   boolean,
  esta_sitio_prohibido          boolean,
  id_sitio_prohibido            bigint[],
  observaciones                 varchar(255),
  foto_1                        varchar(255),
  foto_2                        varchar(255),
  foto_3                        varchar(255),
  id_solicitud_autorizacion     bigint,
  ip                            varchar(255),
  id_usuario_edita              bigint,
  fecha_edita                   date,
  constraint pk_visita_administrativa primary key (id)
);

create table sisdep_social.visita_domiciliaria (
  id                            bigint generated by default as identity not null,
  id_visitador                  bigint,
  fecha_asignacion              date,
  fecha_visita                  date,
  id_tipo                       bigint,
  id_vehiculo                   bigint,
  id_usuario_asigna             bigint,
  id_ventero                    bigint,
  id_franja                     bigint,
  constraint pk_visita_domiciliaria primary key (id)
);

create table sisdep_ventero.visita_seguimiento (
  id                            bigint generated by default as identity not null,
  fecha                         date,
  atiente_titular               boolean,
  cumple_medidas                boolean,
  cumple_tipologia              boolean,
  cumple_horario                boolean,
  id_ventero                    bigint,
  constraint pk_visita_seguimiento primary key (id)
);


# --- !Downs

drop table if exists sisdep_operativa.acta_inventario cascade;

drop table if exists sisdep_general.actividad_economica_tipologica cascade;

drop table if exists sisdep_operativa.actividad_operativa cascade;

drop table if exists sisdep_general.actividad_prohibida cascade;

drop table if exists sisdep_general.adicionales_amoblamiento cascade;

drop table if exists sisdep_ventero.amoblamiento cascade;

drop table if exists sisdep_operativa.archivos_sector_interno cascade;

drop table if exists sisdep_regulaciones.vw_asignacion_modulos cascade;

drop table if exists sisdep_social.aspectos_economicos cascade;

drop table if exists sisdep_social.aspectos_familiares cascade;

drop table if exists sisdep_social.aspectos_poblacionales cascade;

drop table if exists sisdep_social.aspectos_seguridad_social cascade;

drop table if exists sisdep_social.aspectos_vivienda cascade;

drop table if exists sisdep_general.aviso_publicitario cascade;

drop table if exists sisdep_general.aviso_publicitario_apro_economico cascade;

drop table if exists sisdep_general.barrio cascade;

drop table if exists sisdep_general.capacidad_diferencial cascade;

drop table if exists sisdep_regulaciones.caracterizacion_ixi cascade;

drop table if exists sisdep_general.causal_estudio cascade;

drop table if exists sisdep_general.clase_venta cascade;

drop table if exists sisdep_general.comuna cascade;

drop table if exists sisdep_social.concepto_vulnerabilidad cascade;

drop table if exists sisdep_general.convenio cascade;

drop table if exists sisdep_general.cubierta cascade;

drop table if exists sisdep_social.datos_personales cascade;

drop table if exists sisdep_ventero.datos_venta cascade;

drop table if exists sisdep_operativa.descongestion cascade;

drop table if exists sisdep_general.dia_semana cascade;

drop table if exists sisdep_general.direccion cascade;

drop table if exists sisdep_operativa.elemento_entregado cascade;

drop table if exists sisdep_general.elemento_medicion cascade;

drop table if exists sisdep_operativa.entidad_apoyo cascade;

drop table if exists sisdep_operativa.entidad_apoyo_operativa cascade;

drop table if exists sisdep_general.entidad_jubilacion cascade;

drop table if exists sisdep_operativa.entrega cascade;

drop table if exists sisdep_general.eps cascade;

drop table if exists sisdep_general.escolaridad cascade;

drop table if exists sisdep_general.estado cascade;

drop table if exists sisdep_general.estado_autorizacion cascade;

drop table if exists sisdep_general.estado_civil cascade;

drop table if exists sisdep_general.estado_recurso cascade;

drop table if exists sisdep_social.estudio_socio_economico cascade;

drop table if exists sisdep_social.vw_estudios_por_ventero cascade;

drop table if exists sisdep_operativa.evidencia_recuperacion cascade;

drop table if exists sisdep_social.evidencias_oferta cascade;

drop table if exists sisdep_general.exento_retribucion cascade;

drop table if exists sisdep_operativa.fase_indicador cascade;

drop table if exists sisdep_general.finalidad_valla cascade;

drop table if exists sisdep_general.fondo_pension cascade;

drop table if exists sisdep_general.franja_horaria cascade;

drop table if exists sisdep_administracion.grupo cascade;

drop table if exists sisdep_general.grupo_comunitario cascade;

drop table if exists sisdep_general.grupo_poblacional cascade;

drop table if exists sisdep_general.grupo_sisben cascade;

drop table if exists sisdep_general.indicador_parametro cascade;

drop table if exists sisdep_operativa.indicadores_sector_interno cascade;

drop table if exists sisdep_ventero.integrante_nucleo_familiar cascade;

drop table if exists sisdep_regulaciones.intervencion_x_infraestructura cascade;

drop table if exists sisdep_general.item_elemento_publicitario cascade;

drop table if exists sisdep_operativa.item_retencion cascade;

drop table if exists sisdep_general.item_retenido cascade;

drop table if exists sisdep_general.item_valla cascade;

drop table if exists sisdep_general.ixi_anexo cascade;

drop table if exists sisdep_regulaciones.ixi_anexos cascade;

drop table if exists sisdep_general.jornada cascade;

drop table if exists sisdep_general.material_amueblamiento cascade;

drop table if exists sisdep_general.material_pared cascade;

drop table if exists sisdep_general.material_piso cascade;

drop table if exists sisdep_general.material_techo cascade;

drop table if exists sisdep_operativa.miembro_equipo_sector_interno cascade;

drop table if exists sisdep_operativa.miembro_tarea_operativa cascade;

drop table if exists sisdep_general.modulo cascade;

drop table if exists sisdep_administracion.modulo_sistema cascade;

drop table if exists sisdep_general.motivo_autorizacion cascade;

drop table if exists sisdep_general.motivo_intervencion_infraestructura cascade;

drop table if exists sisdep_general.motivo_labora_espacio_publico cascade;

drop table if exists sisdep_general.motivo_recuperacion cascade;

drop table if exists sisdep_general.municipio cascade;

drop table if exists sisdep_general.nacionalidad cascade;

drop table if exists sisdep_social.necesidad cascade;

drop table if exists sisdep_general.nomenclatura_vial cascade;

drop table if exists sisdep_regulaciones.notificacion cascade;

drop table if exists sisdep_general.obtencion_propiedad cascade;

drop table if exists sisdep_general.ocupacion cascade;

drop table if exists sisdep_social.oferta cascade;

drop table if exists sisdep_general.orientacion cascade;

drop table if exists sisdep_general.parentesco cascade;

drop table if exists sisdep_social.participante_oferta cascade;

drop table if exists sisdep_administracion.permisos_x_modulo_x_grupo cascade;

drop table if exists sisdep_ventero.persona cascade;

drop table if exists sisdep_general.persona_atiende cascade;

drop table if exists sisdep_ventero.vw_personas_reporte cascade;

drop table if exists sisdep_general.programa_o_entidad cascade;

drop table if exists sisdep_general.proteccion_constitucional cascade;

drop table if exists sisdep_operativa.reconocimiento_incautacion cascade;

drop table if exists sisdep_regulaciones.recurso cascade;

drop table if exists sisdep_regulaciones.registro_entrega_modulo cascade;

drop table if exists sisdep_social.remision cascade;

drop table if exists sisdep_general.remision_oferta cascade;

drop table if exists sisdep_regulaciones.vw_reporte_modulos cascade;

drop table if exists sisdep_social.vw_reporte_participantes cascade;

drop table if exists sisdep_regulaciones.resolucion cascade;

drop table if exists sisdep_general.resuelve_resolucion cascade;

drop table if exists sisdep_general.resultado_visita_pev cascade;

drop table if exists sisdep_operativa.retencion cascade;

drop table if exists sisdep_operativa.sector_interno cascade;

drop table if exists sisdep_general.sector_modulos cascade;

drop table if exists sisdep_regulaciones.seguimiento cascade;

drop table if exists sisdep_operativa.sensibilizacion cascade;

drop table if exists sisdep_operativa.sensibilizacion_formales cascade;

drop table if exists sisdep_operativa.sensibilizacion_informales cascade;

drop table if exists sisdep_general.servicio_publico cascade;

drop table if exists sisdep_general.sexo cascade;

drop table if exists sisdep_general.sitio_prohibido cascade;

drop table if exists sisdep_regulaciones.solicitud_autorizacion cascade;

drop table if exists sisdep_regulaciones.vw_solicitud_autorizacion_reporte cascade;

drop table if exists sisdep_operativa.solicitud_recuperacion_espacio_publico cascade;

drop table if exists sisdep_operativa.tarea_operativa cascade;

drop table if exists sisdep_general.tenencia_propiedad cascade;

drop table if exists sisdep_general.tenencia_vivienda cascade;

drop table if exists sisdep_ventero.tercero_atiende cascade;

drop table if exists sisdep_general.tipo_afiliacion cascade;

drop table if exists sisdep_general.tipo_capacidad_diferencial cascade;

drop table if exists sisdep_general.tipo_conexion_servicio cascade;

drop table if exists sisdep_general.tipo_conocimiento cascade;

drop table if exists sisdep_general.tipo_cotiza cascade;

drop table if exists sisdep_general.tipo_documento cascade;

drop table if exists sisdep_general.tipo_evidencia cascade;

drop table if exists sisdep_general.tipo_infraccion cascade;

drop table if exists sisdep_general.tipo_instalacion cascade;

drop table if exists sisdep_general.tipo_miembro_sector_interno cascade;

drop table if exists sisdep_general.tipo_misional cascade;

drop table if exists sisdep_general.tipo_mixtura_suelo cascade;

drop table if exists sisdep_general.tipo_modulo cascade;

drop table if exists sisdep_general.tipo_modulo_otro cascade;

drop table if exists sisdep_general.tipo_necesidad cascade;

drop table if exists sisdep_general.tipo_notificacion cascade;

drop table if exists sisdep_general.tipo_ocupacion cascade;

drop table if exists sisdep_general.tipo_oferta cascade;

drop table if exists sisdep_general.tipo_permanencia cascade;

drop table if exists sisdep_general.tipo_persona cascade;

drop table if exists sisdep_general.tipo_pobreza cascade;

drop table if exists sisdep_general.tipo_publicidad cascade;

drop table if exists sisdep_general.tipo_recurso cascade;

drop table if exists sisdep_general.tipo_sensibilizacion cascade;

drop table if exists sisdep_general.tipo_solicitud cascade;

drop table if exists sisdep_general.tipo_vehiculo cascade;

drop table if exists sisdep_general.tipo_visita cascade;

drop table if exists sisdep_general.tipo_vivienda cascade;

drop table if exists sisdep_general.tipologia_familiar cascade;

drop table if exists sisdep_general.tipologia_original cascade;

drop table if exists sisdep_general.tipologia_transitoria cascade;

drop table if exists sisdep_administracion.usuario cascade;

drop table if exists sisdep_general.valores_apgar cascade;

drop table if exists sisdep_general.vehiculo cascade;

drop table if exists sisdep_ventero.ventero cascade;

drop table if exists sisdep_regulaciones.visita_administrativa cascade;

drop table if exists sisdep_social.visita_domiciliaria cascade;

drop table if exists sisdep_ventero.visita_seguimiento cascade;

